/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.h.zapt

#pragma once

#include <app/ConcreteAttributePath.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <app/util/basic-types.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Attributes.h>
#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/DeltadelfinAnimationGradient/AttributeIds.h>
#include <clusters/DeltadelfinAnimationGradient/ClusterId.h>
#include <clusters/DeltadelfinAnimationGradient/Enums.h>
#include <clusters/DeltadelfinAnimationGradient/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace DeltadelfinAnimationGradient {
namespace Attributes {

namespace DisplayMode {
struct TypeInfo
{
    using Type             = chip::app::Clusters::DeltadelfinAnimationGradient::DisplayModeEnum;
    using DecodableType    = chip::app::Clusters::DeltadelfinAnimationGradient::DisplayModeEnum;
    using DecodableArgType = chip::app::Clusters::DeltadelfinAnimationGradient::DisplayModeEnum;

    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayMode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayMode
namespace CurrentAnimation {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::CurrentAnimation::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace CurrentAnimation
namespace CurrentGradient {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::CurrentGradient::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace CurrentGradient
namespace AnimationCount {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AnimationCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AnimationCount
namespace GradientCount {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::GradientCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace GradientCount
namespace TransitionTimeMs {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::TransitionTimeMs::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace TransitionTimeMs
namespace GeneratedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::GeneratedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
};
} // namespace GeneratedCommandList
namespace AcceptedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::AcceptedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
};
} // namespace AcceptedCommandList
namespace AttributeList {
struct TypeInfo : public Clusters::Globals::Attributes::AttributeList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
};
} // namespace AttributeList
namespace FeatureMap {
struct TypeInfo : public Clusters::Globals::Attributes::FeatureMap::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
};
} // namespace FeatureMap
namespace ClusterRevision {
struct TypeInfo : public Clusters::Globals::Attributes::ClusterRevision::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
};
} // namespace ClusterRevision

struct TypeInfo
{
    struct DecodableType
    {
        static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }

        CHIP_ERROR Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path);

        Attributes::DisplayMode::TypeInfo::DecodableType displayMode =
            static_cast<chip::app::Clusters::DeltadelfinAnimationGradient::DisplayModeEnum>(0);
        Attributes::CurrentAnimation::TypeInfo::DecodableType currentAnimation = static_cast<uint8_t>(0);
        Attributes::CurrentGradient::TypeInfo::DecodableType currentGradient   = static_cast<uint8_t>(0);
        Attributes::AnimationCount::TypeInfo::DecodableType animationCount     = static_cast<uint8_t>(0);
        Attributes::GradientCount::TypeInfo::DecodableType gradientCount       = static_cast<uint8_t>(0);
        Attributes::TransitionTimeMs::TypeInfo::DecodableType transitionTimeMs = static_cast<uint16_t>(0);
        Attributes::GeneratedCommandList::TypeInfo::DecodableType generatedCommandList;
        Attributes::AcceptedCommandList::TypeInfo::DecodableType acceptedCommandList;
        Attributes::AttributeList::TypeInfo::DecodableType attributeList;
        Attributes::FeatureMap::TypeInfo::DecodableType featureMap           = static_cast<uint32_t>(0);
        Attributes::ClusterRevision::TypeInfo::DecodableType clusterRevision = static_cast<uint16_t>(0);
    };
};
} // namespace Attributes
} // namespace DeltadelfinAnimationGradient
} // namespace Clusters
} // namespace app
} // namespace chip
