/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/data-model/NullObject.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/DeltadelfinAnimationGradient/ClusterId.h>
#include <clusters/DeltadelfinAnimationGradient/CommandIds.h>
#include <clusters/DeltadelfinAnimationGradient/Enums.h>
#include <clusters/DeltadelfinAnimationGradient/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace DeltadelfinAnimationGradient {
namespace Commands {
// Forward-declarations so we can reference these later.

namespace SetAnimation {
struct Type;
struct DecodableType;
} // namespace SetAnimation

namespace SetGradient {
struct Type;
struct DecodableType;
} // namespace SetGradient

namespace SetDisplayMode {
struct Type;
struct DecodableType;
} // namespace SetDisplayMode

} // namespace Commands

namespace Commands {
namespace SetAnimation {
enum class Fields : uint8_t
{
    kId = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::SetAnimation::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }

    uint8_t id = static_cast<uint8_t>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::SetAnimation::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr bool kIsFabricScoped = false;

    uint8_t id = static_cast<uint8_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace SetAnimation
namespace SetGradient {
enum class Fields : uint8_t
{
    kId               = 0,
    kTransitionTimeMs = 1,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::SetGradient::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }

    uint8_t id                = static_cast<uint8_t>(0);
    uint16_t transitionTimeMs = static_cast<uint16_t>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::SetGradient::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr bool kIsFabricScoped = false;

    uint8_t id                = static_cast<uint8_t>(0);
    uint16_t transitionTimeMs = static_cast<uint16_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace SetGradient
namespace SetDisplayMode {
enum class Fields : uint8_t
{
    kMode = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::SetDisplayMode::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }

    DisplayModeEnum mode = static_cast<DisplayModeEnum>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::SetDisplayMode::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::DeltadelfinAnimationGradient::Id; }
    static constexpr bool kIsFabricScoped = false;

    DisplayModeEnum mode = static_cast<DisplayModeEnum>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace SetDisplayMode
} // namespace Commands
} // namespace DeltadelfinAnimationGradient
} // namespace Clusters
} // namespace app
} // namespace chip
